questionnaire = [
    {"question": "The capital of Australia is Sydney.",
     "answer": "False"},
    {"question": "The Great Wall of China is visible from space.",
     "answer": "False"},
    {"question": "Humans have walked on the Moon.",
     "answer": "True"},
    {"question": "The Pacific Ocean is the largest ocean on Earth.",
     "answer": "True"},
    {"question": "The human body has four lungs.",
     "answer": "False"},
    {"question": "Lightning never strikes the same place twice.",
     "answer": "False"},
    {"question": "The chemical symbol for gold is Au.",
     "answer": "True"},
    {"question": "An octopus has three hearts.",
     "answer": "True"},
    {"question": "Mount Everest is the tallest mountain in the world.",
     "answer": "True"},
    {"question": "Bats are blind.",
     "answer": "False"},
    {"question": "The Eiffel Tower is located in Berlin.",
     "answer": "False"},
    {"question": "The Sun is a star.",
     "answer": "True"},
    {"question": "Water boils at 100°C at sea level.",
     "answer": "True"},
    {"question": "Sharks are mammals.",
     "answer": "False"},
    {"question": "Venus is the closest planet to the Sun.",
     "answer": "False"},
    {"question": "The currency of Japan is the Yen.",
     "answer": "True"},
    {"question": "A group of lions is called a pride.",
     "answer": "True"},
    {"question": "Sound travels faster than light.",
     "answer": "False"},
    {"question": "The human skeleton is made up of over 200 bones.",
     "answer": "True"},
    {"question": "Bananas grow on trees.",
     "answer": "False"},
]